#!/bin/bash
set -e;

# Generator for the PatternData.h file

SCRIPTDIR="$(dirname "$0")";

CALC="$SCRIPTDIR/tools/calcpatterns.sh";
DATDIR="$SCRIPTDIR/data";

{
cat <<EOF;
#ifndef PATTERNDATA_H_INCLUDED
#define PATTERNDATA_H_INCLUDED

#include <avr/pgmspace.h>

// Auto-generated by PatternData.gen.sh

#ifdef NO_PATTERNS
EOF

"$CALC" "$DATDIR/NoPatterns.dat" "$DATDIR"/*.dat;

cat <<EOF;
#elifdef REDUCED_PATTERNS
EOF

"$CALC" "$DATDIR/ReducedPatterns.dat" "$DATDIR"/*.dat;

cat <<EOF;
#else
EOF

"$CALC" "$DATDIR/Patterns.dat" "$DATDIR"/*.dat;

cat <<EOF;
#endif

#endif
EOF
} > "$SCRIPTDIR/PatternData.h";
