#!/bin/bash
set -e;

# Generator for the Logo.h file

SCRIPTDIR="$(dirname "$0")";
TOOLSDIR="$SCRIPTDIR/../../../tools";
DATADIR="$SCRIPTDIR/../data";

CALC="$TOOLSDIR/calcbitmap.sh";
IMG="$DATADIR/logo.png";

{
cat <<EOF;
#ifndef LOGO_H_INCLUDED
#define LOGO_H_INCLUDED

#include <avr/pgmspace.h>

// Auto-generated by Logo.gen.sh

static PROGMEM const uint8_t LOGO[] = {
EOF

"$CALC" "$IMG";

cat <<EOF;
};

#endif
EOF
} > "$SCRIPTDIR/Logo.h";
