#!/bin/bash
set -e;

# Generator for the CompressedShip.h file

SCRIPTDIR="$(dirname "$0")";
TOOLSDIR="$SCRIPTDIR/../../../tools";
DATADIR="$SCRIPTDIR/../data";

CALC="$TOOLSDIR/calccompressedbitmap.sh";
IMG="$DATADIR/Burrumbeet.png";

{
cat <<EOF;
#ifndef COMPRESSED_SHIP_H_INCLUDED
#define COMPRESSED_SHIP_H_INCLUDED

#include <ProgMem.h>

// Auto-generated by CompressedShip.gen.sh

static PROGMEM const uint8_t COMPRESSED_SHIP[] = {
EOF

"$CALC" "$IMG" "81" 128;

cat <<EOF;
};

#endif
EOF
} > "$SCRIPTDIR/CompressedShip.h";
