#!/bin/bash
set -e;

# Generator for the FontVariable.h file

SCRIPTDIR="$(dirname "$0")";
TOOLSDIR="$SCRIPTDIR/../../tools";
DATADIR="$SCRIPTDIR/data";

CALC_WIDTH="$TOOLSDIR/charwidths.sh";
CALC_DATA="$TOOLSDIR/calcbitmap.sh";
IMG="$DATADIR/variablefont.png";

{
cat <<EOF;
#ifndef FONTVARIABLE_H_INCLUDED
#define FONTVARIABLE_H_INCLUDED

#ifdef ARDUINO
#  include <ProgMem.h>
#else
#  include <ProgMem/ProgMem.h>
#endif

// Auto-generated by FontVariable.gen.sh

// Variable-width (height 8) font
static PROGMEM const uint8_t FONTVARIABLE_DATA[] = {
	// data section defines:
	//  FONTHEIGHT
	//  LINEHEIGHT
	//  ASCII START CHAR (inclusive)
	//  ASCII END CHAR (inclusive)
	//  DATA LAYOUT:
	//    0x00 = 1 bitmap image, chars from left-to-right
	//    0x01 = 1 bitmap image per character
	//    0x02 = 1 2D bitmap image, chars left-to-right, top-to-bottom, with width given below
	//  WIDTHS:
	//    layout 0x00: one int per char
	//    layout 0x01: one int for all chars
	//    layout 0x02: one int for all chars then one for # chars per line
	8, 8, 0x20, 0x7F, 0x00,
EOF

"$CALC_WIDTH" "$IMG";

echo "	,";

"$CALC_DATA" "$IMG" "18";

cat <<EOF;
};
#define FONTVARIABLE_IMG (FONTVARIABLE_DATA + 5 + (0x7F - 0x20) + 1)
#define FONTVARIABLE_MASK (nullptr)

#endif
EOF
} > "$SCRIPTDIR/FontVariable.h";
