#!/bin/bash
set -e;

# Generator for the PatternData.h file

SCRIPTDIR="$(dirname "$0")";
TOOLSDIR="$SCRIPTDIR/../../tools";
DATADIR="$SCRIPTDIR/data";

CALC="$TOOLSDIR/calcpatterns.sh";

{
cat <<EOF;
#ifndef PATTERNDATA_H_INCLUDED
#define PATTERNDATA_H_INCLUDED

#ifdef ARDUINO
#  include <ProgMem.h>
#else
#  include <ProgMem/ProgMem.h>
#endif

// Auto-generated by PatternData.gen.sh

#ifdef NO_PATTERNS
EOF

"$CALC" "$DATADIR/NoPatterns.dat" "$DATADIR"/*.dat;

cat <<EOF;
#elifdef REDUCED_PATTERNS
EOF

"$CALC" "$DATADIR/ReducedPatterns.dat" "$DATADIR"/*.dat;

cat <<EOF;
#else
EOF

"$CALC" "$DATADIR/Patterns.dat" "$DATADIR"/*.dat;

cat <<EOF;
#endif

#endif
EOF
} > "$SCRIPTDIR/PatternData.h";
